### ISSUE TITLE
One question about the encoder

### ISSUE THREAD

**Issue by typoverflow** [rraileanu/policy-dynamics-value-functions#3]
Hello, 
thank you for releasing the code. I have one question about the attention-based encoder used in this work. As far as I know, for a sequential input whose shape is (batch_size, length, E1), the shape of the output after the attention layer will be (batch_size, length, E2). I'm wondering how did you reduce the dim1 (which is `length`) to obtain an embedding for a sequence? Is this related to the `mean(1)` op in the following snippet? 
https://github.com/rraileanu/policy-dynamics-value-functions/blob/90c1aa26228103edf8b01d6bcddb70dc37a73e25/embedding_networks.py#L97

**Comment by rraileanu** [comment]
Yes, we take the average over all elements in the sequence (so over the "length" dimension) to get an embedding for each sequence.

**Comment by typoverflow** [comment]
I see. Thanks for your explanation.
